# Generated by Django 4.2.1 on 2023-05-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qayerdan', models.CharField(choices=[('Toshkent sh', 'Toshkent sh'), ('Toshkent', 'Toshkent'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Andijon', 'Andijon'), ("Farg'ona", "Farg'ona"), ('Namangan', 'Namangan'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ("Qoraqalpog'iston AR", "Qoraqalpog'iston AR")], max_length=255)),
                ('Qayerga', models.CharField(choices=[('Toshkent sh', 'Toshkent sh'), ('Toshkent', 'Toshkent'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Andijon', 'Andijon'), ("Farg'ona", "Farg'ona"), ('Namangan', 'Namangan'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ("Qoraqalpog'iston AR", "Qoraqalpog'iston AR")], max_length=255)),
                ('Orinlar_soni', models.IntegerField(verbose_name="O'rinlar soni")),
                ('Kun', models.DateField()),
                ('Narx', models.IntegerField()),
                ('Vaqt', models.TimeField()),
            ],
        ),
    ]
