# Generated by Django 4.2.1 on 2023-06-19 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Taklif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qayerdan', models.CharField(choices=[('Toshkent sh', 'Toshkent sh'), ('Toshkent', 'Toshkent'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Andijon', 'Andijon'), ("Farg'ona", "Farg'ona"), ('Namangan', 'Namangan'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ("Qoraqalpog'iston AR", "Qoraqalpog'iston AR")], max_length=255)),
                ('Qayerga', models.CharField(choices=[('Toshkent sh', 'Toshkent sh'), ('Toshkent', 'Toshkent'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxandaryo', 'Surxandaryo'), ('Andijon', 'Andijon'), ("Farg'ona", "Farg'ona"), ('Namangan', 'Namangan'), ('Sirdaryo', 'Sirdaryo'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ("Qoraqalpog'iston AR", "Qoraqalpog'iston AR")], max_length=255)),
                ('Orinlar_soni', models.IntegerField(verbose_name="Bo'sh o'rinlar soni")),
                ('Kun', models.DateField()),
                ('Narx', models.IntegerField()),
                ('Vaqt', models.TimeField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familiya', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('car_model', models.CharField(choices=[('Cobalt', 'Cobalt'), ('Nexia 3', 'Nexia 3'), ('Lacetti', 'Lacetti'), ('Jentra', 'Jentra'), ('Nexia 2', 'Nexia 2'), ('Malibu', 'Malibu'), ('Epika', 'Epika'), ('Spark', 'Spark'), ('Nexia 1', 'Nexia 1'), ('Malibu', 'Malibu'), ('Malibu 2', 'Malibu 2'), ('Kaptiva', 'Kaptiva'), ('Onix', 'Onix'), ('Matiz', 'Matiz'), ('Damas', 'Damas'), ('boshqa model', 'boshqa model')], max_length=255, verbose_name='Avtomobil modeli')),
                ('plate_number', models.CharField(max_length=255, verbose_name='Avtomobil raqami')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
