# Generated by Django 4.2.1 on 2023-09-24 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0002_alter_profile_driver_alter_taklif_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
