# Generated by Django 4.2.1 on 2023-09-24 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0003_alter_profile_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taklif',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.profile'),
        ),
    ]
