# Generated by Django 4.2.1 on 2023-09-24 05:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0004_alter_profile_driver_alter_taklif_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taklif',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
